language: node_js
node_js:
  - 8
  - 9
sudo: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
script:
  - npm run ci-test
notifications:
  email: false
